// SPDX-License-Identifier: AGPL-3.0-only

package libmain

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/signal"
	"runtime"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/go-kit/log"
	"github.com/go-kit/log/level"
	"github.com/grafana/dskit/ballast"
	"github.com/grafana/dskit/flagext"
	"github.com/grafana/dskit/instrument"
	dslog "github.com/grafana/dskit/log"
	"github.com/grafana/dskit/middleware"
	"github.com/grafana/dskit/server"
	"github.com/grafana/dskit/tracing"
	"github.com/prometheus/client_golang/prometheus"
	"go.uber.org/atomic"

	"github.com/grafana/db-auth-gateway/pkg/gateway"
	"github.com/grafana/db-auth-gateway/pkg/util"
	"github.com/grafana/db-auth-gateway/pkg/util/usage"
)

// configureLogger initialises and configures the main gokit logger and server logger
func configureLogger(cfg *server.Config, logWriter io.Writer) (log.Logger, log.Logger) {
	l := newDefaultLogger(cfg.LogFormat, logWriter)

	// when using the default logger, skip 3 stack frames.
	mainLog := log.With(l, "caller", log.Caller(3))
	// Add the level filter last to avoid unnecessary allocations for caller https://github.com/go-kit/log/issues/14
	mainLog = level.NewFilter(mainLog, cfg.LogLevel.Option)

	// serverLog wraps log function, skip 4 stack frames to get caller information.
	// this works in go 1.12, but doesn't work in versions earlier.
	// it will always shows the wrapper function generated by compiler
	// marked <autogenerated> in old versions.
	serverLogKit := log.With(l, "caller", log.Caller(4))
	// Add the level filter last to avoid unnecessary allocations for caller https://github.com/go-kit/log/issues/14
	serverLog := level.NewFilter(serverLogKit, cfg.LogLevel.Option)

	return mainLog, serverLog
}

// newDefaultLogger creates a new gokit logger with the configured level and format
func newDefaultLogger(format string, logWriter io.Writer) log.Logger {
	logger := dslog.NewGoKitWithWriter(format, logWriter)

	// return a Logger without caller information, shouldn't use directly
	return log.With(logger, "ts", log.DefaultTimestampUTC)
}

func Main() {
	var (
		printHelp               bool
		enableH2C               bool
		shutdownDelay           time.Duration
		gatewayConfig           gateway.Config
		serverConfig            server.Config
		instrumentationConfig   util.InstrumentationServerConfig
		readinessConfig         util.ReadinessServerConfig
		ballastMBs              int
		sInstrumentationBuckets string
		mutexProfileFraction    int
		blockProfileRate        int
	)

	flag.BoolVar(&printHelp, "help", false, "Print help.")
	flag.BoolVar(&printHelp, "h", false, "Print help.")
	flag.BoolVar(&enableH2C, "enable-h2c", false, "Enable h2c.  This is required for HTTP2/GRPC without TLS.")
	flag.DurationVar(
		&shutdownDelay,
		"shutdown-delay",
		0,
		"How long to wait between SIGTERM and shutdown. After receiving SIGTERM, proxy will report not-ready status via readiness handler.",
	)
	flag.IntVar(&ballastMBs, "mem-ballast-size-mbs", 0, "Size of memory ballast to allocate in MBs.")
	flag.StringVar(&sInstrumentationBuckets, "instrumentation.histogram-buckets", "", "Set of buckets to be used for server, and downstream response time histograms")
	flag.IntVar(&mutexProfileFraction, "debug.mutex-profile-fraction", 0, "Fraction at which mutex profile vents will be reported, 0 to disable")
	flag.IntVar(&blockProfileRate, "debug.block-profile-rate", 0, "Fraction of goroutine blocking events that are reported in the blocking profile. 1 to include every blocking event in the profile, 0 to disable.")
	flag.StringVar(&gatewayConfig.Overrides.Path, "overrides-path", "", "Comma separated paths to files that contains runtime reloadable per-tenant overrides config.")
	flag.DurationVar(&gatewayConfig.Overrides.ReloadPeriod, "overrides-reload-period", 15*time.Second, "Duration to use as the reload period for the runtime reloadable per-tenant overrides.")
	flagext.RegisterFlags(&gatewayConfig, &serverConfig, &instrumentationConfig, &readinessConfig)

	usageConfigs := []interface{}{&gatewayConfig, &serverConfig, &instrumentationConfig, &readinessConfig}
	flag.CommandLine.Usage = func() { _ = usage.Usage(usageConfigs...) }

	flag.Parse()

	if printHelp {
		// Print available parameters to stdout, so that users can grep/less them easily.
		flag.CommandLine.SetOutput(os.Stdout)
		if err := usage.Usage(usageConfigs...); err != nil {
			fmt.Fprintf(os.Stderr, "error printing usage: %s\n", err)
			os.Exit(1)
		}
		os.Exit(0)
	}

	if mutexProfileFraction > 0 {
		runtime.SetMutexProfileFraction(mutexProfileFraction)
	}
	if blockProfileRate > 0 {
		runtime.SetBlockProfileRate(blockProfileRate)
	}

	var mainLogger log.Logger
	mainLogger, serverConfig.Log = configureLogger(&serverConfig, os.Stderr)
	exitOnError := util.NewCheckFatalHandler(mainLogger, nil)

	backend := gatewayConfig.Backend
	backendDashGateway := backend + "-gateway"

	switch backend {
	case gateway.Mimir:
	case gateway.Loki:
	case gateway.Tempo:
	case gateway.Pyroscope:
		serverConfig.MetricsMessageSizeNativeHistograms = true
	default:
		exitOnError(
			errors.New("invalid backend"),
			"flag '--backend' must be set to a valid backend",
		)
	}

	// Allocate a block of memory to alter GC behaviour. See https://github.com/golang/go/issues/23044
	ballast := ballast.Allocate(ballastMBs * 1024 * 1024)

	// Derive the metrics namespace: use the config override if set, else derive from backend.
	metricsNamespace := gatewayConfig.MetricsNamespace
	if metricsNamespace == "" {
		metricsNamespace = strings.ReplaceAll(backend, "-", "_")
	}
	// Register the namespace based on set up backend
	serverConfig.MetricsNamespace = metricsNamespace
	// Enable native histograms for enabled scrapers with 10% bucket growth.
	serverConfig.MetricsNativeHistogramFactor = 1.1
	// Ensure instrumentation is not registered on this server
	serverConfig.RegisterInstrumentation = false

	if len(sInstrumentationBuckets) != 0 {
		var instrumentationBuckets []float64
		for _, value := range strings.Split(sInstrumentationBuckets, ",") {
			value = strings.TrimSpace(value)

			if f, err := strconv.ParseFloat(value, 64); err != nil {
				err = fmt.Errorf(fmt.Sprintf("failed to parse %s as float", value), err)
				exitOnError(err, "error registering custom instrumentation histogram buckets")
			} else {
				instrumentationBuckets = append(instrumentationBuckets, f)
			}
		}
		instrument.DefBuckets = instrumentationBuckets
	}

	// Setting the environment variable JAEGER_AGENT_HOST enables tracing
	trace, err := tracing.NewOTelOrJaegerFromEnv(backendDashGateway, mainLogger)
	exitOnError(err, "error initializing tracing backend")
	defer func() { _ = trace.Close() }()

	signalHandler := newSignalHandler(shutdownDelay, mainLogger)
	serverConfig.SignalHandler = signalHandler
	// Allow returning errors with HTTP 4xx status codes.
	serverConfig.ReportHTTP4XXCodesInInstrumentationLabel = true

	if gatewayConfig.EnableHTTPWriteTimeoutRequestCancellation {
		// Applying dskit's write timeout middleware to do request context termination. This is a known issues in Go's
		// http.Server, as noted in https://github.com/golang/go/issues/59602, that the WriteTimeout configured in http.Server doens't cancel the request's context.
		serverConfig.HTTPMiddleware = append(serverConfig.HTTPMiddleware, middleware.NewTimeoutMiddleware(serverConfig.HTTPServerWriteTimeout, "Server timed out", mainLogger))
	}

	server, err := server.New(serverConfig)
	exitOnError(err, "error initializing server")

	if enableH2C {
		protocols := new(http.Protocols)
		protocols.SetHTTP1(true)
		protocols.SetHTTP2(true)
		protocols.SetUnencryptedHTTP2(true)
		server.HTTPServer.Protocols = protocols
	}

	readinessHandler := util.NewReadinessHandler(signalHandler, mainLogger)

	// Set up the readiness handler to pass loadbalancer health checks
	server.HTTP.Path("/").Methods("GET").HandlerFunc(readinessHandler)

	authenticator, err := gateway.NewAuthenticator(gatewayConfig.Auth)
	exitOnError(err, "invalid auth configuration")

	api, err := gateway.NewAPI(gatewayConfig, authenticator, prometheus.DefaultRegisterer, mainLogger)
	exitOnError(err, "error initializing gateway server")

	// Start the healthcheck service if any healthchecks are configured.
	if hc := api.HealthChecker(); hc != nil {
		exitOnError(hc.StartAsync(context.Background()), "error starting healthcheck service")
		defer func() {
			hc.StopAsync()
			// Wait a short time for graceful shutdown.
			shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer shutdownCancel()
			_ = hc.AwaitTerminated(shutdownCtx)
		}()
	}

	instrumentationServer, err := util.NewInstrumentationServer(instrumentationConfig)
	exitOnError(err, "error initializing instrumentation server")
	defer instrumentationServer.Stop()

	err = api.RegisterRoutes(server.HTTP)
	exitOnError(err, "route registration error")

	readinessServer, err := util.NewReadinessServer(readinessConfig, http.HandlerFunc(readinessHandler), mainLogger)
	exitOnError(err, "error initializing readiness server")
	defer readinessServer.Stop()

	err = server.Run()
	exitOnError(err, "server error")
	server.Shutdown()

	runtime.KeepAlive(ballast)
}

func newSignalHandler(shutdownDelay time.Duration, logger log.Logger) *serverSignalHandler {
	return &serverSignalHandler{
		quit:          make(chan struct{}),
		shutdownDelay: shutdownDelay,
		logger:        logger,
	}
}

type serverSignalHandler struct {
	quit          chan struct{}
	ready         atomic.Bool
	shutdownDelay time.Duration
	logger        log.Logger
}

func (dh *serverSignalHandler) Loop() {
	dh.ready.Store(true)

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	defer signal.Stop(sigs)

	for {
		select {
		case <-dh.quit:
			return

		case <-sigs:
			level.Info(dh.logger).Log("msg", "=== received SIGINT/SIGTERM ===", "sleep", dh.shutdownDelay)

			// Not ready anymore.
			dh.ready.Store(false)
			if dh.shutdownDelay > 0 {
				time.Sleep(dh.shutdownDelay)
			}

			level.Info(dh.logger).Log("msg", "shutting down")
			return
		}
	}
}

func (dh *serverSignalHandler) Stop() {
	close(dh.quit)
}

func (dh *serverSignalHandler) Ready() bool {
	return dh.ready.Load()
}
